title: Barlingshult
description: Småbruk i natursköna Glaskogen, Värmland. Fossilfri odling av bär, frukt och grönsaker för biologisk mångfald – med nordiska bin, lantrasdjur samt försäljning av frön och plantor.
author:
  name: Jeremy Karlsson
  email: karlsson@jeremy.se
  url: https://jeremy.se
